# config.py
DEFAULT_TIMEOUT = 30
SHORT_TIMEOUT = 5
POLL_INTERVAL = 3
OTP_MAX_WAIT = 60

MAILBOX_PREFIX_LEN = 4
MAIL_DOMAIN = "mailsac.com"
FIRSTNAME_LEN = 6
LASTNAME_LEN = 6
DEFAULT_PASSWORD = "SecurePassword123"

CHROME_HEADLESS = False
CHROME_BINARY_ARGS = []
